### ISSUE TITLE
PersistenceException when trying to GET array of comments from database

### ISSUE THREAD

**Issue by jcoady9** [sbonner1/RateMyDrink#42]
/backend/
persist.PersistenceException: Transaction failed
	at persist.DerbyDatabase.executeTransaction(DerbyDatabase.java:764)
	at persist.DerbyDatabase.getComments(DerbyDatabase.java:462)
	at controllers.GetComments.getComments(GetComments.java:18)
	at com.example.shanembonner.RateMyDrink.Servlets.MyServlet.doGet(MyServlet.java:102)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.sql.SQLException: At least one parameter to the current statement is uninitialized.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeQuery(Unknown Source)
	at persist.DerbyDatabase$11.execute(DerbyDatabase.java:470)
	at persist.DerbyDatabase$11.execute(DerbyDatabase.java:462)
	at persist.DerbyDatabase.doExecuteTransaction(DerbyDatabase.java:779)
	at persist.DerbyDatabase.executeTransaction(DerbyDatabase.java:762)
	... 22 more
Caused by: ERROR 07000: At least one parameter to the current statement is uninitialized.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.BaseActivation.throwIfMissingParms(Unknown Source)
	at org.apache.derby.exe.acf81e0010x014cxde2ex3112x00000d438f100.reinit(Unknown Source)
	at org.apache.derby.impl.sql.execute.BaseActivation.execute(Unknown Source)
	at org.apache.derby.impl.sql.GenericActivationHolder.execute(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 29 more

**Comment by sbonner1** [comment]
should be fixed
